version: '3.7'
services:
  mysql:
    container_name: mysql
    ports:
      - '${MYSQL_ROOT_PORT}:${MYSQL_ROOT_PORT}'
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql:/var/lib/mysql
  server:
    container_name: server
    links:
      - mysql
    depends_on:
      - mysql
    env_file: .env
    ports:
      - '4000:4000'
    command: npm start
    build:
      context: ./server
      dockerfile: Dockerfile
      args:
        - DATABASE_URL=${DATABASE_URL}
    volumes:
      - './server:/usr/src/server'
      - '/usr/src/server/node_modules'
    environment:
      NODE_ENV: development
      DATABASE_URL: ${DATABASE_URL}
      APP_SECRET: ${APP_SECRET}
      CLIENT_URL: ${CLIENT_URL}
  client:
    container_name: client
    depends_on:
      - server
    ports:
      - '3000:3000'
    build: ./client
    volumes:
      - './client:/usr/src/client'
      - '/usr/src/client/node_modules'
      - '/usr/src/client/.next'
volumes:
  mysql:
