version: '3'
services:
  client-prod:
    container_name: client-prod
    ports:
      - '80:80'
    build:
      context: ./client
      dockerfile: Dockerfile.prod
  server-prod:
    container_name: server-prod
    env_file: .env
    ports:
      - '4000:4000'
    command: npm start
    build:
      context: ./server
      dockerfile: Dockerfile.prod
