version: '3'
services:
  client:
    ports:
      - '3000:3000'
      - '35729:35729'
    command: npm start
    build: ./client
    #volumes: # For webpack dev server to use our local files
    #  - ./client:/usr/src/client
  server:
    env_file: .env
    command: npm start
    build: ./server
  prisma:
    env_file: .env
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        managementApiSecret: ${PRISMA_MANAGEMENT_API_SECRET}
        port: 4466
        databases:
          default:
            connector: mysql
            host: mysql
            port: ${MYSQL_ROOT_PORT}
            user: ${MYSQL_ROOT_USER}
            password: ${MYSQL_ROOT_PASSWORD}
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql: ~
