version: '3'
services:
  client:
    container_name: client
    ports:
      - '3000:3000'
      - '35729:35729'
    command: npm start
    build: ./client
    volumes:
      - './client:/usr/src/client'
      - '/usr/src/client/node_modules'
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
  server:
    container_name: server
    env_file: .env
    ports:
      - '4000:4000'
    command: npm start
    build: ./server
    volumes:
      - './server:/usr/src/server'
      - '/usr/src/server/node_modules'
    environment:
      - NODE_ENV=development
  prisma:
    container_name: prisma
    env_file: .env
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        managementApiSecret: ${PRISMA_MANAGEMENT_API_SECRET}
        port: 4466
        databases:
          default:
            connector: mysql
            host: mysql
            port: ${MYSQL_ROOT_PORT}
            user: ${MYSQL_ROOT_USER}
            password: ${MYSQL_ROOT_PASSWORD}
  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql: ~
